export const NORMALIZE_COURSE: Record<string, string> = {
    // AD / AI / ML / DS Mappings (2025 & Historical)
    "AD Artificial Intel, Data Sc": "AI & Data Science",
    "ARTIFICIAL INTELLIGENCE AND DATA SCIENCE": "AI & Data Science",
    "ARTIFICIAL INTELLIGENCE": "AI & Data Science",
    "B TECH IN ARTIFICIAL INTELLIGENCE AND DATA SCIENCE": "AI & Data Science",
    "B TECH IN ARTIFICIAL INTELLIGENCE AND DATA SCIENCE ": "AI & Data Science",
    "ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING": "CS - AI & Machine Learning",
    "B TECH IN ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING": "CS - AI & Machine Learning",
    "AI Artificial Intelligence": "CS - AI & Machine Learning",
    "B TECH IN ARTIFICIAL INTELLIGENCE": "AI & Data Science",
    "B.TECH IN COMPUTER SCIENCE AND ARTIFICIAL INTELLIGENCE": "CS - Artificial Intelligence",

    // Data Science Wildcards
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(D ATA SCIENCE)": "CS - Data Science",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(DAT A SCIENCE)": "CS - Data Science",
    "COMPUTER SCIENCE AND ENGINEERING(D ATA SCIENCE)": "CS - Data Science",
    "COMPUTER SCIENCE AND ENGINEERING(DAT A SCIENCE)": "CS - Data Science",
    "B TECH (HONS) COMPUTER SCIENCE AND ENGINEERING(D ATA SCIENCE)": "CS - Data Science",
    "CS Data Science": "CS - Data Science",
    "DS Comp. Sc. Engg- Data Sc.": "CS - Data Science",
    "DATA SCIENCES": "CS - Data Science",
    "DATA SCIENCE": "CS - Data Science",
    "DC Data Sciences": "CS - Data Science",
    "BZ B Tech in DS": "CS - Data Science",
    "BF B Tech in DS": "CS - Data Science",
    "LD B Tech in DS": "CS - Data Science",

    // Biotechnology
    "BT Bio Technology": "Biotechnology",
    "BIO- TECHNOLOGY": "Biotechnology",
    "B TECH IN BIO- TECHNOLOGY": "Biotechnology",
    "B.Tech In BIOTECHNOLOG Y & BIO- ENGINEERING": "Biotechnology",
    "B.Tech In BIOTECHNOLOGY & BIO- ENGINEERING": "Biotechnology",
    "BIOTECHNOLOGY": "Biotechnology",
    "BIO-TECHNOLOGY": "Biotechnology",

    // Computer Science & Core
    "CS Computers": "Computer Science & Engineering",
    "COMPUTER SCIENCE AND ENGINEERING": "Computer Science & Engineering",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING": "Computer Science & Engineering",
    "B TECH IN COMPUTER SCIENCE": "Computer Science & Engineering",
    "CS-Computer Science": "Computer Science & Engineering",
    "B TECH IN COMPUTER SCIENCE & ENGG (ARTIFICIAL INTELLIGENCE AND FUTURE TECHNOLOGIES )": "CS - AI & Future Tech",
    "B TECH IN COMPUTER SCIENCE & ENGG (ARTIFICIAL INTELLIGENCE AND FUTURE TECHNOLOGIES)": "CS - AI & Future Tech",
    "B TECH IN COMPUTER SCIENCE & ENGINEERING (ARTIFICAL INTELLIGENCE & MACHINE LEARNING)": "CS - AI & Machine Learning",
    "B TECH IN COMPUTER SCIENCE (CLOUD COMPUTING)": "CS - Cloud Computing",
    "B TECH IN COMPUTER SCIENCE (CYBER SECURITY)": "CS - Cyber Security",
    "B TECH IN COMPUTER SCIENCE (DATA SCIENCE)": "CS - Data Science",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(A RTIFICIAL INTELLIGENCE AND DATA SCIENCE)": "AI & Data Science",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(ARTI FICIAL INTELLIGENCE AND DATA SCIENCE)": "AI & Data Science",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(B LOCK CHAIN)": "CS - Blockchain",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(BLO CK CHAIN)": "CS - Blockchain",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(C YBER SECURITY)": "CS - Cyber Security",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(CYB ER SECURITY)": "CS - Cyber Security",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(I OT INCLUDING BLOCK CHAIN)": "CS - IoT & Blockchain",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(I OT)": "CS - IoT",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(IOT INCLUDING BLOCK CHAIN)": "CS - IoT & Blockchain",
    "B TECH IN COMPUTER SCIENCE AND ENGINEERING(IOT)": "CS - IoT",
    "B TECH IN COMPUTER SCIENCE AND INFORMATION TECHNOLOGY": "CS & Info Tech",
    "B TECH IN COMPUTER SCIENCE AND TECHNOLOGY": "CS & Technology",
    "B TECH IN COMPUTER SCIENCE AND TECHNOLOGY(B IG DATA)": "CS - Big Data",
    "B TECH IN COMPUTER SCIENCE AND TECHNOLOGY(BIG DATA)": "CS - Big Data",
    "B TECH IN COMPUTER SCIENCE AND TECHNOLOGY(D EV OPS)": "CS - DevOps",
    "B TECH IN COMPUTER SCIENCE AND TECHNOLOGY(DEV OPS)": "CS - DevOps",
    "B Tech in Computer Science (Information Security)": "CS - Information Security",
    "B.TECH IN COMPUTER ENGINEERING(S OFTWARE PRODUCT DEVELOPMENT)": "CS - Software Product Dev",
    "B.TECH IN COMPUTER ENGINEERING(SOF TWARE PRODUCT DEVELOPMENT)": "CS - Software Product Dev",
    "B.TECH IN COMPUTER SCIENCE AND ENGG (ROBOTICS)": "CS - Robotics",
    "B.TECH IN COMPUTER SICENCE AND ENGG (DATA ANALYTICS)": "CS - Data Analytics",
    "B.Tech in COMPUTER SCIENCE & ENGG (Business Systems)": "CS - Business Systems",
    "B.Tech in Computer Science (Internet of Things)": "CS - IoT",
    "B.Tech in Computer Science and Engineering(Clou d Computing)": "CS - Cloud Computing",
    "B.Tech in Computer Science and Engineering(Cloud Computing)": "CS - Cloud Computing",
    "B.Tech in Computer Science and Engineering(Dev Ops)": "CS - DevOps",
    "B.Tech in Computer Science and Engineering(Full Stack Development)": "CS - Full Stack Dev",
    "COMPUTER SCIENCE": "Computer Science & Engineering",
    "COMPUTER SCIENCE & TECHNOLOGY": "CS & Technology",
    "COMPUTER SCIENCE AND BUSINESS SYSTEMS": "CS - Business Systems",
    "COMPUTER SCIENCE AND DESIGN": "CS - Design",
    "BTECH IN COMPUTER SCIENCE AND BUSINESS SYSTEMS": "CS - Business Systems",
    "BTECH IN COMPUTER SCIENCE AND DESIGN": "CS - Design",
    "CB Comp. Sc. and Bus Sys.": "CS - Business Systems",
    "DL B.TECH IN CS": "Computer Science & Engineering",
    "DM B.TECH IN CS NW": "CS - Networks",
    "BW B Tech in CS": "Computer Science & Engineering",

    // AI & ML (Additional Mappings)
    "CA CS (AI, Machine Learning)": "CS - AI & Machine Learning",
    "AIML": "CS - AI & Machine Learning",
    "B Tech in Computer Science(AI &ML)": "CS - AI & Machine Learning",
    "BH B Tech in AI": "CS - AI & Machine Learning",
    "COMPUTER SCIENCE AND ENGG (ARTIFICIAL INTELLIGENCE)": "CS - Artificial Intelligence",
    "COMPUTER SCIENCE AND ENGG(ARTIFICIA L INTELLIGENCE AND MACHINE LEARNING)": "CS - AI & Machine Learning",
    "COMPUTER SCIENCE AND ENGG(ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING)": "CS - AI & Machine Learning",
    "COMPUTER APPLICATIONS": "COMPUTER SCIENCE AND ENGINEERING (ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING)",
    "CYBER SECURITY": "CS - Cyber Security",
    "CY C. Cyber Security": "CS - Cyber Security",
    "CY CS - Cyber Security": "CS - Cyber Security",
    "CY C.S. Cyber Security": "CS - Cyber Security",
    "CY CS- Cyber Security": "CS - Cyber Security",
    "COMPUTER SCIENCE AND ENGINEERING (AIML)": "CS - AI & Machine Learning",
    "CD Computer Sc. and Disgn": "CS - Design",
    "CD Computer Sc. and Design": "CS - Design",
    "CS - Business Systems.": "CS - Business Systems",
    "COMPUTER SCIENCE AND ENGINEERING(A RTIFICAL INTELLIGENCE & DATA SCIENCE)": "AI & Data Science",
    "COMPUTER SCIENCE AND ENGINEERING(ARTI FICAL INTELLIGENCE & DATA SCIENCE)": "AI & Data Science",

    // Electronics & Others
    "EC Electronics": "Electronics & Communication",
    "ELECTRONICS AND COMMUNICATION ENGINEERING": "Electronics & Communication",
    "B TECH IN ELECTRONICS & COMMUNICATION ENGINEERING": "Electronics & Communication",
    "B TECH IN ELECTRONICS & COMMUNICATIO N ENGINEERING": "Electronics & Communication",
    "B TECH IN ELECTRONICS & COMPUTER ENGINEERING": "Electronics & Computer Engg",
    "B.TECH IN ELECTRONICS ENGINEERING": "Electronics Engineering",
    "B.TECH IN ELECTRONICS ENGINEERING (VLSI AND EMBEDDED SYSTEM)": "Electronics - VLSI & Embedded",
    "B.TECH IN EMBEDDED SYSTEM AND VLSI": "Electronics - VLSI & Embedded",
    "BTECH IN ELECTRONICS ENGINEERING(V LSI DESIGN & TECHNOLOGY)": "Electronics - VLSI",
    "BTECH IN ELECTRONICS ENGINEERING(VLSI DESIGN & TECHNOLOGY)": "Electronics - VLSI",
    "ELECTRONICS & COMMUNICATION ENGINEERING(IND USTRIAL INTEGTATED)": "Electronics & Comm (Ind. Integ)",
    "ELECTRONICS & COMPUTER ENGINEERING": "Electronics & Computer Engg",
    "ELECTRONICS & COMPUTER SCIENCE": "Electronics & Computer Science",
    "ELECTRONICS & INSTRUMENTATI ON ENGINEERING": "Electronics & Instrumentation",
    "ELECTRONICS & INSTRUMENTATION ENGINEERING": "Electronics & Instrumentation",
    "ELECTRONICS AND COMMUNICATIO N (ADVANCED COMMUNICATIO N TECHNOLOGY)": "Electronics - Advanced Comm",
    "ELECTRONICS AND COMMUNICATIO N ENGG": "Electronics & Communication",
    "ELECTRONICS AND COMMUNICATIO N ENGG (VLSI DESIGN AND TECHNOLOGY)": "Electronics - VLSI",
    "ELECTRONICS AND COMMUNICATION (ADVANCED COMMUNICATION TECHNOLOGY)": "Electronics - Advanced Comm",
    "ELECTRONICS AND COMMUNICATION ENGG": "Electronics & Communication",
    "ELECTRONICS AND COMMUNICATIO N ENGINEERING": "Electronics & Communication",
    "ELECTRONICS AND COMMUNICATION ENGG (VLSI DESIGN AND TECHNOLOGY)": "Electronics - VLSI",
    "ELECTRONICS AND INSTRUMENTATI ON ENGINEERING": "Electronics & Instrumentation",
    "ELECTRONICS AND INSTRUMENTATION ENGINEERING": "Electronics & Instrumentation",
    "ELECTRONICS AND TELECOMMUNIC ATION ENGINEERING": "Electronics & Telecommunication",
    "ELECTRONICS AND TELECOMMUNICAT ION ENGINEERING": "Electronics & Telecommunication",
    "ELECTRONICS ENGINEERING(V LSI DESIGN & TECHNOLOGY)": "Electronics - VLSI",
    "ELECTRONICS ENGINEERING(VLSI DESIGN & TECHNOLOGY)": "Electronics - VLSI",
    "BB B Tech in EC": "Electronics & Communication",

    // Information Science
    "IE Info.Science": "Information Science",
    "INFORMATION SCIENCE AND ENGINEERING": "Information Science",
    "B TECH IN INFORMATION SCIENCE & TECHNOLOGY": "Information Science",
    "B TECH IN INFORMATION SCIENCE ENGINEERING": "Information Science",
    "INFORMATION SCIENCE": "Information Science",
    "Information Science": "Information Science",
    "IZ INFORMATION SCIENCE": "Information Science",
    "CU B Tech in IS": "Information Science",

    // Mechanical
    "ME Mechanical": "Mechanical Engineering",
    "MECHANICAL ENGINEERING": "Mechanical Engineering",
    "B TECH IN MECHANICAL ENGINEERING": "Mechanical Engineering",
    "B TECH IN MECHATRONICS ENGINEERING": "Mechatronics",
    "B TECH IN ROBOTIC ENGINEERING": "Robotics",
    "B TECH IN ROBOTICS AND AUTOMATION": "Robotics & Automation",
    "B TECH IN ROBOTICS ENGINEERING": "Robotics",
    "B Tech in ROBOTICS AND ARTIFICIAL INTELLIGENCE": "Robotics & AI",
    "B.TECH IN MECHANICAL AND AEROSPACE ENGINEERING": "Mechanical & Aerospace",
    "BTECH IN MECHANICAL AND SMART MANUFACTURING": "Mechanical & Smart Mfg",
    "DB B Tech in ME": "Mechanical Engineering",

    // Civil
    "CE Civil": "Civil Engineering",
    "CIVIL ENGINEERING": "Civil Engineering",
    "B TECH IN CIVIL ENGINEERING": "Civil Engineering",
    "B.TECH IN CIVIL CONSTRUCTION AND SUSTAINABILITY ENGINEERING": "Civil - Const. & Sustainability",
    "CIVIL ENGINEERING (KANNADA MEDIUM)": "Civil Engineering (Kannada)",
    "CIVIL ENGINEERING WITH COMPUTER APPLICATION": "Civil - Computer App",
    "CIVIL ENVIRONMENTA L ENGINEERING": "Civil - Environmental",
    "CIVIL ENVIRONMENTAL ENGINEERING": "Civil - Environmental",
    "CK Civil Engg (Kannada)": "Civil Engineering (Kannada)",
    "CV Civil Environment Engg": "Civil - Environmental",
    "BP B Tech in CE": "Civil Engineering",

    // Others
    "SE Aero Space Engg": "AERO SPACE ENGINEERING",
    "SE Aero Space Engg.": "AERO SPACE ENGINEERING",
    "SE Aero Space Engs.": "AERO SPACE ENGINEERING",
    "AE Aeronaut.Engg": "Aeronautical Engineering",
    "AU Automobile": "Automobile Engineering",
    "CH Chemical": "Chemical Engineering",
    "EE Electrical": "Electrical & Electronics",
    "IT Instrument. Tech.": "Instrumentation Technology",
    "AERO SPACE ENGINEERING": "AERO SPACE ENGINEERING",
    "AEROSPACE ENGINEERING": "AERO SPACE ENGINEERING",
    "AERONAUTICAL ENGINEERING": "Aeronautical Engineering",
    "AGRICULTURE ENGINEERING": "Agricultural Engineering",
    "AUTOMATION AND ROBOTICS": "Automation & Robotics",
    "AUTOMOBILE ENGINEERING": "Automobile Engineering",
    "AUTOMOTIVE ENGINEERING": "Automotive Engineering",
    "BIO-MEDICAL ENGINEERING": "Biomedical Engineering",
    "BIOMEDICAL AND ROBOTIC ENGINEERING": "Biomedical & Robotic",
    "CHEMICAL ENGINEERING": "Chemical Engineering",
    "CONSTRUCTION TECHNOLOGY AND MGMT": "Construction Tech & Mgmt",
    "ELECTRICAL & COMPUTER ENGINEERING": "Electrical & Computer Engg",
    "ELECTRICAL & ELECTRONICS ENGINEERING": "Electrical & Electronics",
    "ELECTRICAL AND ELECTRONICS ENGINEERING": "Electrical & Electronics",
    "EI Elec. Inst. Engg": "Electronics & Instrumentation",
    "ET Elec. Telecommn. Engg.": "Electronics & Telecommunication",
    "ET Elec. Telecomm. Engg.": "Electronics & Telecommunication",
    "ELECTRONICS AND INSTRUMENTATION ENGG": "Electronics & Instrumentation",
    "INDUSTRIAL & PRODUCTION ENGINEERING": "Industrial & Production",
    "INDUSTRIAL ENGINEERING & MANAGEMENT": "INDUSTRIAL ENGINEERING & MANAGEMENT",
    "INDUSTRIAL ENGINEERING AND MANAGEMENT": "INDUSTRIAL ENGINEERING & MANAGEMENT",
    "INDUSTRIAL ENGINEERING AND MANAGEMENT'": "INDUSTRIAL ENGINEERING & MANAGEMENT",
    "IM Ind. Engg. Mgmt.": "INDUSTRIAL ENGINEERING & MANAGEMENT",
    "IM Ind. Engg. Mgmt": "INDUSTRIAL ENGINEERING & MANAGEMENT",

    // Unmapped old short codes
    "IC CS-IoT, Cyber Security": "CS - IoT & Cyber Security",
    "EV EC Engg(VLSI Design)": "Electronics - VLSI",
    "CF CS(Artificial Intel.)": "CS - Artificial Intelligence",
    "BM Bio Medical": "Biomedical Engineering",
    "MD Med.Elect.": "Medical Electronics",
    "RI Robotics and AI": "Robotics & AI",
    "EB EAT": "Electronics - Advanced Comm",
    "OT Industrial IOT": "Industrial IoT",
    "EN Environmental": "Environmental Engineering",
    "IP Ind.Prodn.": "Industrial & Production",
    "PT Polymer Tech.": "Polymer Science & Technology",
    "EL Electronics, Instr. Tech.": "Electronics & Instrumentation",
    "ST Silk Tech.": "Silk Technology",
    "TX Textiles": "Textiles Technology",
    "TC Telecommn.": "Electronics & Telecommunication",
    "ES Electronics and Computer": "Electronics & Computer Engg",
    "EA Agriculture Engineering": "Agricultural Engineering",
    "BR BioMed. and Robotic Engg": "Biomedical & Robotic",
    "CC Computer and Comm. Engg.": "Computer & Communication Engg",
    "CO Computer Engineering": "Computer Engineering",
    "CR Ceramics": "Ceramics & Cement Engineering",
    "CT Const. Tech. Mgmt.": "Construction Tech & Mgmt",
    "SA Smart Agritech": "Smart Agritech",
    "RO Auto. And Robot.": "Automation & Robotics",
    "RA Robotics and Automation": "Robotics & Automation",
    "MT Mechatronics": "Mechatronics",
    "MK Mechanical Engg (Kannada)": "Mechanical Engineering (Kannada)",
    "MM Mechanical, Smart Manf.": "Mechanical & Smart Mfg",
    "MR Marine Engineering": "Marine Engineering",
    "MI Mining Engineering": "Mining Engineering",
    "mn Mining Engineering": "Mining Engineering",
    "ER Electrical and Computer": "Electrical & Computer Engg",
    "CG Computer Science and Tech": "CS & Technology",
    "IO CS- Internet of Things": "CS - IoT",

    // Unmapped 2025 full names
    "ROBOTICS AND ARTIFICIAL INTELLIGENCE": "Robotics & AI",
    "B Tech in Robotics and Artificial Intelligence": "Robotics & AI",
    "MEDICAL ELECTRONICS ENGINEERING": "Medical Electronics",
    "TEXTILES TECHNOLOGY": "Textiles Technology",
    "SILK TECHNOLOGY": "Silk Technology",
    "MINING ENGINEERING": "Mining Engineering",
    "MARINE ENGINEERING": "Marine Engineering",
    "MECHATRONICS": "Mechatronics",
    "ROBOTICS AND AUTOMATION": "Robotics & Automation",
    "INDUSTRIAL IOT": "Industrial IoT",
    "ENVIRONMENTAL ENGINEERING": "Environmental Engineering",
    "ENVIRONMENTA L ENGINEERING": "Environmental Engineering",
    "MECHANICAL ENGINEERING (KANNADA MEDIUM)": "Mechanical Engineering (Kannada)",
    "MECHANICAL AND SMART MANUFACTURING": "Mechanical & Smart Mfg",
    "CERAMICS & CEMENT ENGINEERING": "Ceramics & Cement Engineering",
    "POLYMER SCIENCE & TECHNOLOGY": "Polymer Science & Technology",
    "PRODUCTION ENGINEERING": "Industrial & Production",
    "COMPUTER AND COMMUNICATION ENGINEERING": "Computer & Communication Engg",
    "COMPUTER AND COMMUNICATIO N ENGINEERING": "Computer & Communication Engg",
    "COMPUTER ENGINEERING": "Computer Engineering",
    "COMPUTER SCIENCE AND ENGG(INTERNE T OF THINGS & CYBER SECURITY INCLUDING BLOCK CHAIN TECH)": "CS - IoT & Cyber Security",
    "COMPUTER SCIENCE AND ENGG(INTERNET OF THINGS & CYBER SECURITY INCLUDING BLOCK CHAIN TECH)": "CS - IoT & Cyber Security",
    "COMPUTER SCIENCE AND ENGG(INTERNE T OF THINGS)": "CS - IoT",
    "COMPUTER SCIENCE AND ENGG(INTERNET OF THINGS)": "CS - IoT",
    "COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY)": "CS - Cyber Security",
    "VLSI DESIGN AND EMBEDDED SYSTEMS": "Electronics - VLSI & Embedded",
    "B TECH IN ELECTRICAL & ELECTRONICS ENGINEERING": "Electrical & Electronics",
    "B TECH IN INFORMATION TECHNOLOGY": "Information Technology",
    "B TECH IN AERO SPACE ENGINEERING": "Aerospace Engineering",
    "B TECH IN AERONAUTICAL ENGINEERING": "Aeronautical Engineering",
    "B TECH IN AGRICULTURAL ENGINEERING": "Agricultural Engineering",
    "B TECH IN COMPUTER ENGINEERING": "Computer Engineering",
    "B TECH IN ENERGY ENGINEERING": "Energy Engineering",
    "B TECH IN PETROLEUM ENGINEERING": "Petroleum Engineering",
    "B TECH IN MATHAMATICS AND COMPUTING": "Mathematics & Computing",

    // Remaining unmapped short codes (multi-college)
    "BJ B Tech in EE": "Electrical & Electronics",
    "BK B Tech in EN": "Energy Engineering",
    "BG B Tech in AD": "AI & Data Science",
    "BL B Tech in AS": "Aerospace Engineering",
    "BN B Tech in BD": "Biomedical Engineering",
    "BO B Tech in BT": "Biotechnology",
    "BQ B Tech in CG": "CS & Technology",
    "BU B Tech in CI": "Civil Engineering",
    "BV B Tech in CO": "Computer Engineering",
    "BX B Tech in CY": "CS - Cyber Security",
    "BY B Tech in DO": "CS - DevOps",
    "CL B Tech in EO": "Electronics & Computer Engg",
    "CM B Tech in EV": "Electronics - VLSI",
    "CN B Tech in IB": "CS - IoT & Blockchain",
    "CQ B Tech in IO": "CS - IoT",
    "CW B Tech in IT": "Information Technology",
    "CX B Tech in IY": "CS - IoT & Cyber Security",
    "CZ B Tech in LC": "CS - Cloud Computing",
    "DA B Tech in MC": "Mathematics & Computing",
    "DD B Tech in MS": "Mechatronics",
    "DE B Tech in PE": "Petroleum Engineering",
    "DF B Tech in RA": "Robotics & Automation",
    "DG DESIGN": "Design",
    "DG DG": "Design",
    "DH B Tech in RAI": "Robotics & AI",
    "DI B Tech in RE": "Robotics",
    "DJ B Tech in RO": "Automation & Robotics",
    "DK B Tech in SS": "CS - Software Product Dev",
    "DN B.Tech in VLSI": "Electronics - VLSI & Embedded",
    "AM B Tech in AM": "CS - AI & Machine Learning",
    "LE B Tech in AIML": "CS - AI & Machine Learning",
    "LF B Tech in CC": "CS - Cloud Computing",
    "LG B Tech in CS": "Computer Science & Engineering",
    "LH B Tech in IS": "Information Science",
    "LJ B Tech in BS": "CS - Business Systems",
    "LK B Tech in IOT": "CS - IoT",
    "ZU CYBER SECURITY": "CS - Cyber Security",
    "ZC CSC": "Computer Science & Engineering",
    "ZR COMP.SCE.AND ENG(ART.INT)": "CS - Artificial Intelligence",
    "ZW COMP. SCE. AND ENG (AIML)": "CS - AI & Machine Learning",
    "ZH B TECH IN COMP.SC.ART.INT": "CS - Artificial Intelligence",
    "ZM B.TECH IN COMP.SCI. DESI.": "CS - Design",
    "ZN B.TECH IN PHARM. ENGG.": "Pharmaceutical Engineering",
    "ZO B.TECH IN CS.AND BUSI.SYS": "CS - Business Systems",
    "ZQ B.TECH IN IN.TCH.DAT.ANAL": "Information Technology - Data Analytics",
    "ZV B.TECH.IN INF.TEC.AUG.REA": "Information Technology",
    "ZT B.TECH. IN MECH.SMAR.MANU": "Mechanical & Smart Mfg",
    "ZL CIVIL ENG. WITH COMP.APPL": "Civil - Computer App",
    "ZA B TECH IN AERONAUT. ENGG.": "Aeronautical Engineering",
    "DESIGN": "Design",
    "PLANNING": "Planning",
    "BACHELOR OF PLANNING": "Planning",
    "LA B Plan": "Planning",
    "UP Planning": "Planning",
    "UR Planning": "Planning",
    "AR Architecture": "Architecture",
    "BTECH IN PHARMACEUTICAL ENGINEERING": "Pharmaceutical Engineering",
    "BTECH IN INFORMATION TECHNOLOGY DATA ANALYTICS": "Information Technology - Data Analytics",
    "B.TECH IN Computer Science and Medical Engineering": "CS - Medical Engineering",
    "B.TECH IN ELECTRICAL ENGINEERING AND COMPUTER SCIENCE": "Electrical & Computer Engg",

    // YA-YI series + remaining old codes
    "YA B.TEHIN COM.SCE.ENG(ROBO)": "CS - Robotics",
    "YB B.TECH IN CS.ENG(DAT ANA)": "CS - Data Analytics",
    "YC B.TECH IN EMD. SYS. VLSI": "Electronics - VLSI & Embedded",
    "YD B.TECH IN CS AND ARTI INT": "CS - Artificial Intelligence",
    "YE B.TECH IN CIV.CONST.SUST.": "Civil - Const. & Sustainability",
    "YF B.TECH IN ELECT ENGG. CS.": "Electrical & Computer Engg",
    "YG B.TECH IN EC.ENG.VSLI EMD": "Electronics - VLSI & Embedded",
    "YH ENGINEERING DESIGN": "Engineering Design",
    "YI B.TECH IN MECHANICAL": "Mechanical Engineering",
    "ENGINEERING DESIGN": "Engineering Design",
    "BA B.Tech(Agri.Engg)": "Agricultural Engineering",
    "AT Automotive Engg.": "Automotive Engineering",
    "EZ ELECTRONICS AND COMPUT": "Electronics & Computer Engg",
    "B.Tech in Electrical and Electronics Engineering (Electrical Vehicle Technology)": "Electrical & Electronics",
    "B Tech in Artificial Intelligence and Data Science": "AI & Data Science",
    "B Tech in Civil Engineering": "Civil Engineering",
    "B Tech in Computer Science & Engineering (Artificial Intelligence & Machine Learning)": "CS - AI & Machine Learning",
    "B Tech in Computer Science and Engineering": "Computer Science & Engineering",
    "B Tech in Computer Science and Engineering (Block Chain)": "CS - Blockchain",
    "B Tech in Computer Science and Engineering (Cyber Security)": "CS - Cyber Security",
    "B Tech in Computer Science and Engineering (Data Science)": "CS - Data Science",
    "B Tech in Computer Science and Engineering (IoT)": "CS - IoT",
    "B Tech in Computer Science and Technology (Big Data)": "CS - Big Data",
    "B Tech in Computer Science and Technology (DevOps)": "CS - DevOps",
    "B Tech in Electrical & Electronics Engineering": "Electrical & Electronics",
    "B Tech in Electronics & Communication Engineering": "Electronics & Communication",
    "B Tech in Information Science & Technology": "Information Science",
    "B Tech in Information Science Engineering": "Information Science",
    "B Tech in Mechanical Engineering": "Mechanical Engineering",
    "B Tech in Petroleum Engineering": "Petroleum Engineering",

    // Final unmapped courses
    "B TECH (HONS) COMPUTER SCIENCE AND ENGINEERING(DAT A SCIENCE)": "CS - Data Science",
    "FASHION DESIGN": "Fashion Design",
    "COMMUNICATION DESIGN": "Communication Design",
    "LIFE STYLE AND ACCESSORY DESIGN": "Lifestyle & Accessory Design",
    "INDUSTRIAL DESIGN": "Industrial Design",
};

export const normalizeCourseName = (rawName: string) => {
    if (!rawName) return "";
    const cleaned = rawName.replace(/\n/g, ' ').replace(/\s+/g, ' ').trim();
    return NORMALIZE_COURSE[cleaned] || cleaned;
};
